apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: scale-pilot-config-file
  namespace: <your-namespace>
spec:
  data:
    - remoteRef:
        key: scale-pilot-config-file
      secretKey: config.yaml
  refreshInterval: 30s
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    creationPolicy: Owner
    name: scale-pilot-config-file
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: scale-pilot-env
  namespace: <your-namespace>
spec:
  data:
    - remoteRef:
        key: scale-pilot-env
      secretKey: .env
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    creationPolicy: Owner
    name: scale-pilot-env
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: scale-pilot-eventname
  namespace: <your-namespace>
spec:
  dataFrom:
    - extract:
        key: scale-pilot-eventname
  refreshInterval: 2m
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    creationPolicy: Owner
    name: scale-pilot-eventname  

    