apiVersion: v1
kind: ServiceAccount
metadata:
  name: scale-pilot
  namespace: <your-namespace>
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scale-pilot
  namespace: <your-namespace>
rules:
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scale-pilot
  namespace: <your-namespace>
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: scale-pilot
subjects:
- kind: ServiceAccount
  name: scale-pilot
  namespace: <your-namespace>
---
### Required only if Kong or any HPA in other namespace is to be updated.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scale-pilot
  namespace: kong
rules:
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scale-pilot
  namespace: kong
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: scale-pilot
subjects:
- kind: ServiceAccount
  name: scale-pilot
  namespace: <your-namespace>  
